name: h3
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _r-mutex=1.0.0=anacondar_1
  - _sysroot_linux-64_curr_repodata_hack=3=haa98f57_10
  - binutils_impl_linux-64=2.38=h2a08ee3_1
  - binutils_linux-64=2.38.0=hc2dff05_0
  - blas=1.0=openblas
  - bottleneck=1.3.7=py311hf4808d0_0
  - bwidget=1.9.16=h9eba36c_0
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.7.2=h06a4308_0
  - cairo=1.16.0=hb05425b_5
  - cffi=1.16.0=py311h5eee18b_1
  - curl=8.7.1=hdbd6064_0
  - expat=2.6.2=h6a678d5_0
  - fontconfig=2.14.1=h4c34cd2_2
  - freetype=2.12.1=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - gcc_impl_linux-64=11.2.0=h1234567_1
  - gcc_linux-64=11.2.0=h5c386dc_0
  - gfortran_impl_linux-64=11.2.0=h1234567_1
  - gfortran_linux-64=11.2.0=hc2dff05_0
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - graphite2=1.3.14=h295c915_1
  - gxx_impl_linux-64=11.2.0=h1234567_1
  - gxx_linux-64=11.2.0=hc2dff05_0
  - harfbuzz=4.3.0=hf52aaf7_2
  - icu=73.1=h6a678d5_0
  - jinja2=3.1.4=py311h06a4308_0
  - jpeg=9e=h5eee18b_1
  - kernel-headers_linux-64=3.10.0=h57e8cba_10
  - krb5=1.20.1=h143b758_1
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libcurl=8.7.1=h251f7ec_0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-devel_linux-64=11.2.0=h1234567_1
  - libgcc-ng=14.1.0=h77fa898_0
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=14.1.0=h77fa898_0
  - libiconv=1.16=h5eee18b_3
  - libnghttp2=1.57.0=h2d74bed_0
  - libopenblas=0.3.21=h043d6bf_0
  - libpng=1.6.39=h5eee18b_0
  - libssh2=1.11.0=h251f7ec_0
  - libstdcxx-devel_linux-64=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.5.1=h6a678d5_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxcb=1.16=hd590300_0
  - libxml2=2.10.4=hfdd30dd_2
  - lz4-c=1.9.4=h6a678d5_1
  - make=4.2.1=h1bed415_1
  - markupsafe=2.1.3=py311h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - numexpr=2.8.7=py311h812550d_0
  - numpy=1.26.4=py311h24aa872_0
  - numpy-base=1.26.4=py311hbfb1bba_0
  - openssl=3.0.14=h5eee18b_0
  - pandas=2.2.2=py311ha02d727_0
  - pandoc=2.12=h06a4308_3
  - pango=1.50.7=h05da053_0
  - pcre2=10.42=hebb0a14_1
  - pip=24.0=py311h06a4308_0
  - pixman=0.40.0=h7f8727e_1
  - pthread-stubs=0.3=h0ce48e5_1
  - pybind11-abi=4=hd3eb1b0_1
  - pycparser=2.21=pyhd3eb1b0_0
  - python=3.11.9=h955ad1f_0
  - python-dateutil=2.9.0post0=py311h06a4308_2
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - pytz=2024.1=py311h06a4308_0
  - r-assertthat=0.2.1=r43h6115d3f_0
  - r-base=4.3.1=h1ae530e_0
  - r-base64enc=0.1_3=r43h76d94ec_4
  - r-biocmanager=1.30.22=r43h142f84f_0
  - r-bitops=1.0_7=r43h76d94ec_0
  - r-bslib=0.5.1=r43h6115d3f_0
  - r-cachem=1.0.8=r43h76d94ec_0
  - r-cairo=1.6_1=r43hec52ca5_0
  - r-catools=1.18.2=r43h884c59f_0
  - r-cli=3.6.1=r43h884c59f_0
  - r-clue=0.3_65=r43h76d94ec_0
  - r-cluster=2.1.4=r43h640688f_0
  - r-codetools=0.2_19=r43h6115d3f_0
  - r-colorspace=2.1_0=r43h76d94ec_0
  - r-combinat=0.0_8=r43h142f84f_0
  - r-cpp11=0.4.6=r43h6115d3f_0
  - r-crayon=1.5.2=r43h6115d3f_0
  - r-digest=0.6.33=r43h884c59f_0
  - r-doparallel=1.0.17=r43h6115d3f_0
  - r-dplyr=1.1.3=r43h884c59f_0
  - r-ellipsis=0.3.2=r43h76d94ec_0
  - r-evaluate=0.22=r43h6115d3f_0
  - r-fansi=1.0.5=r43h76d94ec_0
  - r-farver=2.1.1=r43h884c59f_0
  - r-fastmap=1.1.1=r43h884c59f_0
  - r-fontawesome=0.5.2=r43h6115d3f_0
  - r-foreach=1.5.2=r43h6115d3f_0
  - r-fs=1.6.3=r43h884c59f_0
  - r-generics=0.1.3=r43h142f84f_0
  - r-getoptlong=1.0.5=r43h6115d3f_0
  - r-ggplot2=3.4.4=r43h6115d3f_0
  - r-globaloptions=0.1.2=r43h142f84f_0
  - r-glue=1.6.2=r43h76d94ec_0
  - r-gplots=3.1.3=r43h6115d3f_0
  - r-gridbase=0.4_7=r43h6115d3f_4
  - r-gridextra=2.3=r43h6115d3f_0
  - r-gtable=0.3.4=r43h6115d3f_0
  - r-gtools=3.9.4=r43h76d94ec_0
  - r-highr=0.10=r43h6115d3f_0
  - r-htmltools=0.5.6.1=r43h76d94ec_0
  - r-infotheo=1.2.0.1=r43h884c59f_0
  - r-isoband=0.2.7=r43h884c59f_0
  - r-iterators=1.0.14=r43h6115d3f_0
  - r-jquerylib=0.1.4=r43h6115d3f_0
  - r-jsonlite=1.8.7=r43h76d94ec_0
  - r-kernsmooth=2.23_22=r43h640688f_0
  - r-knitr=1.44=r43h6115d3f_0
  - r-labeling=0.4.3=r43h6115d3f_0
  - r-lattice=0.22_5=r43h76d94ec_0
  - r-lifecycle=1.0.3=r43h142f84f_0
  - r-magrittr=2.0.3=r43h76d94ec_0
  - r-mass=7.3_60=r43h76d94ec_0
  - r-matrix=1.6_1.1=r43h76d94ec_0
  - r-memoise=2.0.1=r43h6115d3f_0
  - r-mgcv=1.9_0=r43h76d94ec_0
  - r-mime=0.12=r43h76d94ec_0
  - r-munsell=0.5.0=r43h6115d3f_0
  - r-nlme=3.1_163=r43h640688f_0
  - r-nmf=0.21.0=r43h884c59f_0
  - r-pillar=1.9.0=r43h6115d3f_0
  - r-pkgconfig=2.0.3=r43h6115d3f_0
  - r-pkgmaker=0.32.10=r43h6115d3f_0
  - r-plyr=1.8.9=r43h884c59f_0
  - r-purrr=1.0.2=r43h76d94ec_0
  - r-r6=2.5.1=r43h6115d3f_0
  - r-rappdirs=0.3.3=r43h76d94ec_0
  - r-rcolorbrewer=1.1_3=r43h6115d3f_1
  - r-rcpp=1.0.11=r43h884c59f_0
  - r-registry=0.5_1=r43h6115d3f_0
  - r-reshape2=1.4.4=r43h884c59f_0
  - r-rjson=0.2.21=r43h884c59f_0
  - r-rlang=1.1.1=r43h884c59f_0
  - r-rmarkdown=2.25=r43h6115d3f_0
  - r-rngtools=1.5.2=r43h6115d3f_0
  - r-sass=0.4.7=r43h884c59f_0
  - r-scales=1.2.1=r43h6115d3f_0
  - r-stringi=1.7.12=r43h884c59f_0
  - r-stringr=1.5.0=r43h6115d3f_0
  - r-tibble=3.2.1=r43h76d94ec_0
  - r-tidyr=1.3.0=r43h884c59f_0
  - r-tidyselect=1.2.0=r43h6115d3f_0
  - r-tinytex=0.48=r43h142f84f_0
  - r-utf8=1.2.4=r43h76d94ec_0
  - r-vctrs=0.6.4=r43h884c59f_0
  - r-viridis=0.6.4=r43h6115d3f_0
  - r-viridislite=0.4.2=r43h6115d3f_0
  - r-withr=2.5.1=r43h6115d3f_0
  - r-xfun=0.40=r43h76d94ec_0
  - r-xtable=1.8_4=r43h6115d3f_0
  - r-yaml=2.3.7=r43h76d94ec_0
  - readline=8.2=h5eee18b_0
  - rpy2=3.5.11=py311r43h356210d_0
  - scipy=1.13.1=py311h24aa872_0
  - setuptools=69.5.1=py311h06a4308_0
  - simplegeneric=0.8.1=py311h06a4308_2
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.45.3=h5eee18b_0
  - sysroot_linux-64=2.17=h57e8cba_10
  - tk=8.6.14=h39e8969_0
  - tktable=2.10=h3d55465_1
  - tzdata=2024a=h04d1e81_0
  - tzlocal=5.2=py311h06a4308_0
  - wheel=0.43.0=py311h06a4308_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libx11=1.8.9=hb711507_1
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h27cfd23_1007
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.5=hc292b87_2
prefix: /home/nicolashomberg/miniconda3/envs/h3
